spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: consum-blog-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
server:
  port: 80
mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.faon.springcloud.entities